project:
  type: website
  output-dir: docs

website:
  title: "a-ramji.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

